### ISSUE TITLE
What is '@@'?

### ISSUE THREAD

**Issue by lsby** [sanctuary-js/sanctuary-identity#29]
I noticed the definition in the source code:
```JavaScript
  var prototype = {
    /* eslint-disable key-spacing */
    'constructor':            Identity,
    '@@type':                 identityTypeIdent,
    '@@show':                 Identity$prototype$show,
    'fantasy-land/map':       Identity$prototype$map,
    'fantasy-land/ap':        Identity$prototype$ap,
    'fantasy-land/chain':     Identity$prototype$chain,
    'fantasy-land/reduce':    Identity$prototype$reduce,
    'fantasy-land/traverse':  Identity$prototype$traverse,
    'fantasy-land/extend':    Identity$prototype$extend,
    'fantasy-land/extract':   Identity$prototype$extract
    /* eslint-enable key-spacing */
  };
```
I can understand part of it.
For example, `fantasy-land/map` is a function required by the typeclass `Functor` specified in `Fantasy Land`.
This means that the `sanctuary-identity` structure implements the typeclass `Functor`.
So what is `@@type` and `@@show`, and where is it defined?

Also, I noticed in the source code:
```JavaScript
  //# Identity#@@show :: Showable a => Identity a ~> () -> String
  //.
  //. `show (Identity (x))` is equivalent to `'Identity (' + show (x) + ')'`.
  //.
  //. ```javascript
  //. > show (Identity (['foo', 'bar', 'baz']))
  //. 'Identity (["foo", "bar", "baz"])'
  //. ```
  function Identity$prototype$show() {
    return 'Identity (' + show (this.value) + ')';
  }
```
There is a `Showable`, what is it? It doesn't seem to be in `Fantasy Land`.

**Comment by davidchambers** [comment]
Welcome to the Sanctuary community, @lsby. :wave:

> So what is `@@type` and `@@show`, and where is it defined?

`@@type` provides compatibility with [sanctuary-type-identifiers][1] and, by extension, [`S.type`][2]:

```javascript
> S.type (Identity ([1, 2, 3]))
{
  namespace: Just ("sanctuary-identity"),
  name: 'Identity',
  version: 1
}
```

`@@show` provides compatibility with [sanctuary-show][3] and, by extension, [`S.show`][4]:

```javascript
> S.show (Identity ([1, 2, 3]))
'Identity ([1, 2, 3])'
```

Do not hesitate to ask further questions. :)


[1]: https://github.com/sanctuary-js/sanctuary-type-identifiers
[2]: https://sanctuary.js.org/#type
[3]: https://github.com/sanctuary-js/sanctuary-show
[4]: https://sanctuary.js.org/#show

**Comment by lsby** [comment]
@davidchambers got it, thank you!
